baseURL = "https://luckly.work/"
languageCode = "zh-CN"
title = "早起的年轻人"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = ""  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "luckly"

[params]
  author = "luckly"
  subtitle = "专注于Flutter、Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
  keywords = "Flutter，golang,go语言,go语言笔记,飞雪无情,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Flutter、Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  fancybox = true  #图片点击放大
  beian = "粤ICP备2021号-1"  #添加备案信息
  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  custom_css = ["/css/copy-to-clipboard.css"]
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
[params.image_cdn]
    enable = true
    Host = "https://cdn.jsdelivr.net/gh/ITmxs/ITmxs.github.io"

## 友情链接，可以多个

[[params.links]]
  title = "飞雪无情的博客"
  name = "飞雪无情的博客"
  url = "https://www.flysnow.org/"

[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "itachi's Blog"
  name = "阿林"
  url = "https://itachi.xyz/"

## 侧边栏广告位
[[params.ads]]
  title = "我的CSDN"
  url = "https://blog.csdn.net/qq_39132095?spm=1001.2101.3001.5343"
  img = "https://luckly007.oss-cn-beijing.aliyuncs.com/img/flutter.png"
[[params.ads]]
  title = "我的哔哩哔哩"
  url = "https://space.bilibili.com/480883651"
  img = "https://luckly007.oss-cn-beijing.aliyuncs.com/img/flutter.png"
[[params.ads]]
  title = "我的知乎"
  url = "https://www.zhihu.com/people/yimi-yang-guang-96-65"
  img = "https://luckly007.oss-cn-beijing.aliyuncs.com/img/flutter.png"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "https://github.com/ITmxs/repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

 [[menu.main]]
  name = "分类"
  weight = 30
  identifier = "categories"
  url = "/categories/"
 [[menu.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags/"
 [[menu.main]]
  name = "关于我"
  weight = 50
  identifier = "about"
  url = "/about/"
 [[menu.main]]
  name = "github"
  weight = 60
  identifier = "reading-list"
  url = "https://github.com/ITmxs/"